#!/usr/bin/env bash
# Usage: bash install_llvm


VERSION_NUMBER="21"

if [[ $(uname -s) == 'Darwin' ]] ; then  # macOS
    brew update || true
    brew install flang
    flang --version
else  # Assume Linux

    # Add the LLVM repository
    UBUNTU_CODENAME=$(lsb_release -sc)
    echo "deb http://apt.llvm.org/${UBUNTU_CODENAME}/ llvm-toolchain-${UBUNTU_CODENAME}-${VERSION_NUMBER} main" \
        | sudo tee /etc/apt/sources.list.d/llvm-toolchain-${VERSION_NUMBER}.list

    # Add the GPG key for the LLVM repository
    wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key \
        | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc

    # Install the packages; clang is needed.
    sudo apt update
    sudo apt-get install -y flang-${VERSION_NUMBER} clang-${VERSION_NUMBER} # lld-${VERSION_NUMBER}

    # Verify the installation
    type flang-${VERSION_NUMBER} || \
        { echo "flang-${VERSION_NUMBER} not found after the installation, which probably failed." >&2 ; exit 1; }

    # Set up a symbolic link named flang pointing to flang-${VERSION_NUMBER}
    FLANG_DIR="$(dirname "$(which flang-${VERSION_NUMBER})")"
    cd "$FLANG_DIR" || exit 1
    if [[ -f flang ]]; then
        echo "A flang executable already exists in the same directory as flang-${VERSION_NUMBER}."
        echo "Its version is:"
        flang --version
        echo "Backing up the existing flang executable to flang.bak"
        sudo mv flang flang.bak
    fi
    echo "Creating a symbolic link named flang pointing to flang-${VERSION_NUMBER} in $(pwd)"
    sudo ln -s flang-${VERSION_NUMBER} flang

fi

type flang > /dev/null 2>&1 || \
    { echo "flang not found after the installation, which probably failed." >&2 ; exit 1; }

# Final messages
echo "flang installation completed."
echo -e "\nThe flang version is:\n"
flang --version
echo -e "\nThe path to flang is:\n"
command -v flang
