#!/usr/bin/env bash
# Usage: bash install_llvm


if [[ $(uname -s) == 'Darwin' ]] ; then  # macOS
    brew update || true
    brew install flang
    flang --version
    #export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
else  # Assume Linux

    wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
    echo "deb http://apt.llvm.org/$(lsb_release -sc)/ llvm-toolchain-$(lsb_release -sc)-21 main" | sudo tee /etc/apt/sources.list.d/llvm-toolchain-21.list
    sudo apt update || true
    sudo apt-get install -y clang lldb lld flang
    flang --version
    flang-21 --version

fi

#find -L / -type f -name flang -exec test -x {} \; -print
FLANG=$(find -L /opt -type f -name flang-21 -exec test -x {} \; -print | sort | tail -n 1)
echo "Found flang at: $FLANG"
LLVM_DIR="$(dirname $(dirname $FLANG))"
export PATH=$LLVM_DIR/bin:$PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$LLVM_DIR/lib

# Verify installation
for tool in flang clang clang++; do
    type $tool > /dev/null 2>&1 || \
        { echo "$tool not found after the installation, which probably failed." >&2 ; exit 1; }
done

# Final messages
echo "LLVM installation completed."
for tool in flang clang clang++; do
    echo -e "\nThe $tool version is:\n"
    $tool --version
    echo -e "\nThe path to $tool is:\n"
    command -v $tool
done


# Set environment variable for subsequent steps
# N.B.: The following lines will not work if this script is invoked with sudo.
# Put $LLVM_DIR/bin to the beginning of PATH, in case there is another flang in PATH, e.g., from AOCC.
echo "PATH=$LLVM_DIR/bin:$PATH" >> "$GITHUB_ENV"
echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$LLVM_DIR/lib" >> "$GITHUB_ENV"

## Export relevant environment variables for GitHub Actions
#env | grep -i 'llvm\|flang\|clang' >> "$GITHUB_ENV"
