#!/usr/bin/env bash

if [ ! -d "prima" ]; then
    git clone https://github.com/libprima/prima.git
fi
cd prima
git checkout 70a07b2c98a5503e58923ca151acab2b1bf28aa2
cd fortran/tests
cp -r ../lincoa ./
cp -r ../common ./

COMPILER=$1
FLAG=$2
if [ $FLAG = mmlir ]; then
    FLAG="-mmlir -fdynamic-heap-array"
else
    FLAG="-fno-stack-arrays"
fi

echo "COMPILER: $COMPILER, FLAG: $FLAG"

type $COMPILER
$COMPILER --version

rm -f rtest_i4_r8_d1_tst_c_o1
$COMPILER $FLAG -g \
    -DPRIMA_DEBUGGING=1 -DPRIMA_AGGRESSIVE_OPTIONS=0 -DPRIMA_INTEGER_KIND=32 -DPRIMA_REAL_PRECISION=64 -DPRIMA_QP_AVAILABLE=0 -DPRIMA_TESTDIM="'big'" \
    -o rtest_i4_r8_d1_tst_c_o1 \
    ./common/consts.F90 \
    ./common/infos.f90 \
    ./common/debug.F90 \
    ./common/huge.F90 \
    ./common/inf.F90 \
    ./common/infnan.F90 \
    ./common/memory.F90 \
    ./common/string.f90 \
    ./common/linalg.f90 \
    ./common/univar.f90 \
    ./common/ratio.f90 \
    ./common/redrho.f90 \
    ./common/xinbd.f90 \
    ./common/history.f90 \
    ./common/selectx.f90 \
    ./common/checkexit.f90 \
    ./common/fprint.f90 \
    ./common/message.f90 \
    ./common/preproc.f90 \
    ./common/pintrf.f90 \
    ./common/evaluate.f90 \
    ./common/powalg.f90 \
    ./common/shiftbase.f90 \
    ./lincoa/update.f90 \
    ./lincoa/initialize.f90 \
    ./lincoa/getact.f90 \
    ./lincoa/trustregion.f90 \
    ./lincoa/geometry.f90 \
    ./lincoa/lincob.f90 \
    ./lincoa/lincoa.f90 \
    ./testsuite/param.f90 \
    ./testsuite/rand.f90 \
    ./testsuite/noise.f90 \
    ./testsuite/prob.f90 \
    ./testsuite/datetime.f90 \
    test_lincoa.f90 \
    test.F90

gdb -return-child-result -batch -iex "set auto-load safe-path /"  -ex run -ex where -ex quit ./rtest_i4_r8_d1_tst_c_o1
